services:
  - docker

script:
  - docker run -v `pwd`:/mnt --workdir /mnt registry.gitlab.com/oer/docker/emacs-reveal:3.1 emacs --batch --load elisp/publish.el

deploy:
  provider: pages:git
  local_dir: public
  token:
    secure: SiKr83VO5kE8OYHkJLfbyOLVWkXlB85ZB8Rt+x7LE6uBofnS7Xe/OhESqphss37/+tncX1FWmyi9zYnJR8ihA8j1fC9IB69sX4oBYfrln1UnzEyRumGDsvjlgK28j4BMZYb4wM9g//NEu7Swf58l3dr1Z6fOXN+aD9m0XSYRrYQCpkf1TdjupjbtkAqT6xReuyiXjL+25kkFOlgr8dL/iTY87P+CV3Khvr60I6Egvf32gBWt7RE61ymOv4NmShv/lH1SCurJ5GDmQAIv9A07XGHXoEz0T4/H/m8ToDtbK+H5iE3E9zRDTlmYNUVGxVBs748nQWh+7PYaNYNiAijzjpVve6STvlsdiX418Am12NXybu9RGOn3buAQYruaIUKFYKwnxY8XXDeObxaiPvJPk9OUD3JueRikX+IRVK+iXPbTcNmrQ0pe+6o+re444fChASTwnTnmZQ5ceYEidu/kYy3B3+Nhiw7W9yib9et6soxnSeUVdOJt+gfIRqKOE0wW82Xwk29fb5i0hwp41CJlppOy4G76+MmBkWveUtLXgOZzU1E3eS8IXPpQoN/4ow/nVIP4O0Y6mfVICDZmlbU36awhbn9v9xfwJeQjfd5rRo0YKzPJI/RJE6MIQe7yH9qNF5GSUGC+jSov82KzIFQ6MAHY4tS1rvJxzHUjJDDVClI=
  edge: true
