services:
- docker
script:
- docker run -v `pwd`:/mnt --workdir /mnt registry.gitlab.com/oer/docker/emacs-reveal:3.1
  emacs --batch --load elisp/publish.el
deploy:
  provider: pages:git
  local_dir: public
  edge: true
  token:
    secure: M2M0x2WQpgBpu9xY1MENnJw2lA27ZuVlE9YnydwTR1M14otTvlSFcowsalSkjERuCzbvdMQcUQvGePu5Jqe/Bp1xChGFLuO+yjMEOTIaHpmTk+hSDaWPkylXo0SXT3U+GnVY5iA9W8kBNeEVMU1n3cF9fVwntp82obuniPOMB5s1Lno7F91wn+6XjJeR3mBOcFRIgv1nEXf2IGlba4bUNait+EQnv4KswQKbU9Rmr8tlNi6d4JGwAdr9tRAQccWkNE4NctN5IVdRRlWyfJmTSm+D0uNnE7WgngZtIkCeJJO0Obzt2I5CRn5eDh9Zmf2W75TLOj1TpUJXlJD82RXpSYaVQTkJeI54aOY+3wb1fY+PDS/Tl6LWFmwO93qBL883xh2GyaRg1Lr02HmufomROq7tJIA8Sly/QuKWiA+zBOz4dX2LQmHd4OR5S1Ih4UTw9C7lMx4thrRmDKyKKoaEiyAlStgrHU0FmlBvbp5qkGmvxvYD/l69H8x39xrYM8z44n8mvURRJ5Sl07hZZOX1t1MraPhrT8NNr1So9HUzModAmldDwQGf1hf+cuVpoYal9EQ/zpiGqxPkzvQ2xKWhoP410UANk0sl2RZ4I4DDdRxMzo/xES2Rpfpe3cd2okQbcfnjSo8cAo1AgARg40GxdqTfHRfkT303s2z4FkQc+ZQ=
